version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "senzingapi-runtime"
    IMAGE_TAG: "latest"
    ECR_URI: "283428323412.dkr.ecr.us-east-1.amazonaws.com"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_URI/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_URI/$IMAGE_REPO_NAME:$IMAGE_TAG