name: docker-push-containers-to-dockerhub.yaml

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  docker-push-containers-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Build docker image
        uses: Senzing/github-action-docker-buildx-build@latest
        with:
          image-repository: senzing/senzingapi-runtime
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
