name: docker-build-container.yaml

on: [push]

jobs:
  docker-build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Build docker image
        uses: Senzing/github-action-docker-buildx-build@v1
        with:
          image-repository: senzing/senzingapi-runtime
          image-tag: ${{ github.ref_name }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
