name: senzing-cicd-deploy.yaml
on:
  push:
    branches:
      - main
jobs:
  senzing-cicd-deploy:
    name: Deploy to ECR via codebuild
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: senzing-cicd-deploy
          buildspec-override: cicd-deploy/deploy.yml
